# render.yaml - Applying fixes for validation errors

services:
  # --- Cache & Queue Service (Redis) ---
  - type: redis
    name: idcard-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: [] # FIX 1: Added IP allow list

  # --- Backend API Service ---
  - type: web
    name: idcard-api
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    dockerCommand: "sh -c 'npx knex migrate:latest --env production && node index.js'" # FIX 2: Changed to dockerCommand

  # --- Background Worker Service ---
  - type: worker
    name: idcard-worker
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: "node worker.js" # FIX 3: Changed to dockerCommand
  

  # --- Frontend Static Site Service ---
  - type: web
    name: idcard-client
    plan: free
    runtime: static
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    